name: Build Android AAB (App Bundle)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Cordova
      run: |
        npm install -g cordova
        
    - name: Create Cordova Project
      run: |
        # پروجیکٹ بنانا
        cordova create cordova_project com.darseislami.darsenazami "Dars_E_Islami"
        
        # صرف انڈیکس فائل کو کاپی کرنا
        cp index.html cordova_project/www/ 2>/dev/null || true
        
        cd cordova_project
        
        # اینڈرائیڈ 12 پلیٹ فارم جوڑنا
        cordova platform add android@12.0.0
        
        # جدید ایڈموب پلگ ان جوڑنا
        cordova plugin add cordova-plugin-admob-plus --variable APP_ID_ANDROID="ca-app-pub-3940256099942544~3347511713"

    - name: Build Android App Bundle (AAB)
      run: |
        cd cordova_project
        # کلاؤڈ کے نئے گریڈل ورژن (9.x) کو ہٹا کر کورڈووا کا اپنا گریڈل رن کرنا
        unset CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL
        export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-8.7-bin.zip"
        ./platforms/android/gradlew --version || true
        cordova build android --release -- --packageType=bundle

    - name: Upload Finished AAB File
      uses: actions/upload-artifact@v4
      with:
        name: Islamic-Library-AAB
        path: cordova_project/platforms/android/app/build/outputs/bundle/release/*.aab
        
